//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DALLayer.Recources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key on a property could not be found.
        /// </summary>
        public static string ForeignKeyOnPropertyCouldNotFound {
            get {
                return ResourceManager.GetString("ForeignKeyOnPropertyCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not insert.
        /// </summary>
        public static string InsertException {
            get {
                return ResourceManager.GetString("InsertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key on a property could not be found.
        /// </summary>
        public static string KeyOnPropertyCouldNotFound {
            get {
                return ResourceManager.GetString("KeyOnPropertyCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No order with id = {0}.
        /// </summary>
        public static string NoOrderWithId {
            get {
                return ResourceManager.GetString("NoOrderWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stored procedure attribute was found.
        /// </summary>
        public static string NoStoredProcedureAttributeWasFound {
            get {
                return ResourceManager.GetString("NoStoredProcedureAttributeWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Table attribute was found.
        /// </summary>
        public static string NoTableAttributeWasFound {
            get {
                return ResourceManager.GetString("NoTableAttributeWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not finished previous transaction.
        /// </summary>
        public static string NotFinishedPreviousTransaction {
            get {
                return ResourceManager.GetString("NotFinishedPreviousTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required property could not be found.
        /// </summary>
        public static string RequiredPropertyCouldNotFound {
            get {
                return ResourceManager.GetString("RequiredPropertyCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryed commit not opened transaction.
        /// </summary>
        public static string TryedCommitNotOpenedTransaction {
            get {
                return ResourceManager.GetString("TryedCommitNotOpenedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong count of stored procedure parameters.
        /// </summary>
        public static string WrongCountOfStoredProcedureParameters {
            get {
                return ResourceManager.GetString("WrongCountOfStoredProcedureParameters", resourceCulture);
            }
        }
    }
}
